name = "Posets"
uuid = "9a158a65-591e-4f68-ac4f-9ffef2fc51f2"
authors = ["Ed Scheinerman <ers@jhu.edu>"]
version = "0.0.0"

[deps]
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
julia = "1"
Graphs = "1"